### ISSUE TITLE
Adding License needs extra step

### ISSUE THREAD

**Issue by DanielaGawehns** [annakrystalli/rrresearchACCE20#1]
Hey Anna, 

when attaching a license with usethis:: I get an error that I need to set my .Rprofile first. 
No issue really but maybe nice to add to the workshop material?

Cheers,
Daniela

usethis::use_mit_license()
Error: `name` argument is missing.
Set it globally with `options(usethis.full_name = "My name")`probably in your '.Rprofile'.

**Comment by annakrystalli** [comment]
Done!
