### ISSUE TITLE
Link no longer works

### ISSUE THREAD

**Issue by JJFoest** [annakrystalli/rrresearchACCE20#11]
Dear Anna, 

I hope you are well!
I was trying to open the bookdown site, to look up some tips you shared. However, the link seems broken?

Best wishes,
Jessie

**Comment by annakrystalli** [comment]
Hey Jessie! That's strange! The link posted on the repo is still working: https://annakrystalli.me/rrresearchACCE20/

Was the bit.ly link that didn't work?

**Comment by JJFoest** [comment]
Hi Anna,

Wow, it worked. I couldn’t reach your entire .me domain, so perhaps it was a temporary glitch. Thanks a lot, and sorry to bother you!

Cheers,
Jessie

**Comment by annakrystalli** [comment]
Glad it's working now! Hadn't realised it was inaccessible at some point so thanks for letting me know so I could check!
